name: Close Stale Issues
on:
  schedule:
    - cron: "0 11 * * *" # 每天的 11:00 运行
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  close_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-labels: needs more info

          days-before-issue-stale: 60
          days-before-issue-close: 7

          stale-issue-label: stale
          stale-issue-message: >
            该 Issue 需要补充信息，但 60 天内未收到回复。
            如仍需要帮助，请补充所需信息，否则将在 7 天后关闭。

          close-issue-message: >
            由于未按要求补充信息，该 Issue 已被自动关闭。
            如问题仍存在，可在补充完整信息后重新开启。
